# Generated by Django 6.0.1 on 2026-03-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_privacy_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled Post', max_length=255),
            preserve_default=False,
        ),
    ]
